SHOW DATABASES;
CREATE DATABASE Renocrew;
USE Renocrew;
SHOW TABLES;
SELECT * FROM student;
DESC student;

CREATE TABLE Images (
	imgID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    pic MEDIUMBLOB NOT NULL
);

SELECT * FROM Images;    

DROP TABLE Images;

ALTER TABLE Images MODIFY pic LONGBLOB NOT NULL;
DESC Images;
DESC student;

CREATE TABLE Users (
	User_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(30) NOT NULL,
    PassKey VARCHAR(30) NOT NULL
);
SELECT * FROM Users;

DELETE FROM Users WHERE User_ID = 6;

UPDATE Users 
SET PassKey = "password@M19"
WHERE User_ID = 3;

DESC Users;

ALTER TABLE Users
ADD CONSTRAINT FK_Student_ID
FOREIGN KEY (User_ID) REFERENCES student(S_ID);

ALTER TABLE Users
DROP FOREIGN KEY FK_Student_ID;
